### ISSUE TITLE
Create Demo Site

### ISSUE THREAD

**Issue by stevepiercy** [knop-project/knop#23]
Create a demo site of Knop hosted by the kind and generous folks at [Anu Internet Services](http://anu.net/).
# Task List
- [x] Hosting donated by Anu Internet Services
- [x] Configure Lasso 8 and 9
- [x] Register domain name knop-project.org
- [x] Get email address info at knop-project dot org
- [ ] Configure server
- [ ] Create users for those who will SSH onto server to perform work and maintenance
- [ ] Deploy Knop for Lasso 8
- [ ] Deploy Knop for Lasso 9.3
- [ ] Create scripts to wipe and reload data hourly
- [ ] Prevent deletion of the primary demo user
- [ ] Show timer stats that compare performance of version 8 and 9
- [ ] Links to docs, GitHub, Google Group
- [ ] Allow developers to add their name/business (entity) and projects under their entity for review and acceptance on the site
